= webpkr Build Language Reference
:showtitle:
:page-permalink: /dsl-reference/

Webpkr scripts are _configuration scripts_. As the script executes, it configures a tree of configuration nodes. During the evaluation phase, tree nodes are evaluated to generate a `webpack` configuration object.

[WARNING]
Under Development.

== Script Structure
A configuration script is made of up of multiple statements and script blocks. A script block inserts a new node in the the _configuration tree_ and takes optional parameters. If the final parameter is a closure, it is treated as a _configuration closure_ which configures the newly created node. Any optional parameters are available to the node during the subsequent evaluation phase.

Top level script blocks map to top level keys of the `webpack` configuration object. Where there is a potential clash of names (e.g. with `module` or `path`), the script block name is appended with a `$` symbol.

The build script is JavaScript code, and can contain any valid JavaScript, such as method definitions, `require` statements, classes etc.

== Builder/Global Variables

=== `projectDir`
The directory containing the project build file. Defaults to `process.cwd()`.
```javascript
// webpack.config.js
module.exports = require( 'webpkr' )( { projectDir: __dirname } );

```
=== `buildDir`
The build directory of this project where all the output will be generated. Defaults to `projectDir/build`.

== Entry and Context

=== `context( )`
`string`

The base directory for resolving entry points and loaders from configuration. Relative paths are resolved from `projectDir`.

```javascript
// context = projectDir/src
context('src')
```


=== `entry()`
`string | [string] | object { <key>: string | [string] }`

The point or points to enter the application. See link:https://webpack.js.org/configuration/entry-context/#entry[entry]. Webpkr will merge multiple calls to `entry()`:

- Arrays will be merged with arrays or individual strings.
- Objects will merged/extended by key.

[WARNING]
Attempting to merge an array with an object will result in an error.

[header,cols="1a,1a", grid=cols, frame=none, options="header"]
|===
^| webpkr script
^| webpack configuration

|
```javascript
entry('./src/index.js')
entry('./src/another.js')
```

|
```javascript
entry: [
  './src/index.js',
  './src/another.js' ]
```
|===


== Output

The top-level `output` script block configures `webpack` output settings.

```javascript
output(() =>{
  filename( 'bundle.js' )
  path$( 'dist' )
} )
```

[NOTE]
====
To avoid potential name clashes, `output.path` is available as `path$`.
====

- link:https://webpack.js.org/configuration/output/#output-auxiliaryComment[auxiliaryComment(...)]
- link:https://webpack.js.org/configuration/output/#output-chunkFilename[chunkFilename(...)]
- link:https://webpack.js.org/configuration/output/#output-crossOriginLoading[crossOriginLoading(...)]
- link:https://webpack.js.org/configuration/output/#output-chunkLoadTimeout[chunkLoadTimeout(...)]
- link:https://webpack.js.org/configuration/output/#output-devtoolFallbackModuleFilenameTemplate[devtoolFallbackModuleFilenameTemplate(...)]
- link:https://webpack.js.org/configuration/output/#output-devtoolLineToLine[devtoolLineToLine(...)]
- link:https://webpack.js.org/configuration/output/#output-devtoolModuleFilenameTemplate[devtoolModuleFilenameTemplate(...)]
- link:https://webpack.js.org/configuration/output/#output-filename[filename(...)]
- link:https://webpack.js.org/configuration/output/#output-hashDigest[hashDigest(...)]
- link:https://webpack.js.org/configuration/output/#output-hashDigestLength[hashDigestLength(...)]
- link:https://webpack.js.org/configuration/output/#output-hashFunction[hashFunction(...)]
- link:https://webpack.js.org/configuration/output/#output-hashSalt[hashSalt(...)]
- link:https://webpack.js.org/configuration/output/#output-hotUpdateChunkFilename[hotUpdateChunkFilename(...)]
- link:https://webpack.js.org/configuration/output/#output-hotUpdateFunction[hotUpdateFunction(...)]
- link:https://webpack.js.org/configuration/output/#output-hotUpdateMainFilename[hotUpdateMainFilename(...)]
- link:https://webpack.js.org/configuration/output/#output-jsonpFunction[jsonpFunction(...)]
- link:https://webpack.js.org/configuration/output/#output-library[library(...)]
- link:https://webpack.js.org/configuration/output/#output-libraryTarget[libraryTarget(...)]
- link:https://webpack.js.org/configuration/output/#output-libraryExport[libraryExport(...)]
- link:https://webpack.js.org/configuration/output/#output-path$[path$(...)]
- link:https://webpack.js.org/configuration/output/#output-pathinfo[pathinfo(...)]
- link:https://webpack.js.org/configuration/output/#output-publicPath[publicPath(...)]
- link:https://webpack.js.org/configuration/output/#output-sourceMapFilename[sourceMapFilename(...)]
- link:https://webpack.js.org/configuration/output/#output-sourcePrefix[sourcePrefix(...)]
- link:https://webpack.js.org/configuration/output/#output-strictModuleExceptionHandling[strictModuleExceptionHandling(...)]
- link:https://webpack.js.org/configuration/output/#output-umdNamedDefine[umdNamedDefine(...)]

== Module

The top-level `module$` script block configures the `webpack` module key.

```javascript
module$( () => {
  rule( () => { } )
  rule( () => { } )
} )
```

`module$` provides the following script blocks:

=== `rule()`

The `rule` script block defines a rule which is matched to requests when modules are created. Rule blocks are grouped into the `module.rules` array during the evaluation phase.

```javascript
module$( () => {

  rule( () => {
    test( /\.css$/ )
    use( ExtractTextPlugin.extract( {
      fallback: 'style-loader',
      use: 'css-loader',
    } ) )
  } )

  rule( () => {
    test( /\.scss$/ )
    use( ExtractTextPlugin.extract( {
      fallback: 'style-loader',
      use: [
        { loader: 'css-loader' },
        { loader: 'sass-loader' },
      ]
    } ) )
  } )
} )
```

The following script blocks are available within the `rule` script block:

- link:https://webpack.js.org/configuration/module/#rule-enforce[enforce(...)]
- link:https://webpack.js.org/configuration/module/#rule-exclude[exclude(...)]
- link:https://webpack.js.org/configuration/module/#rule-include[include(...)]
- link:https://webpack.js.org/configuration/module/#rule-issuer[issuer(...)]
- link:https://webpack.js.org/configuration/module/#rule-loader[loader(...)]
- link:https://webpack.js.org/configuration/module/#rule-loaders[loaders(...)]
- link:https://webpack.js.org/configuration/module/#rule-oneOf[oneOf(...)]
- link:https://webpack.js.org/configuration/module/#rule-options[options(...)]
- link:https://webpack.js.org/configuration/module/#rule-parser[parser(...)]
- link:https://webpack.js.org/configuration/module/#rule-query[query(...)]
- link:https://webpack.js.org/configuration/module/#rule-resource[resource(...)]
- link:https://webpack.js.org/configuration/module/#rule-resourceQuery[resourceQuery(...)]
- link:https://webpack.js.org/configuration/module/#rule-compiler[compiler(...)]
- link:https://webpack.js.org/configuration/module/#rule-test[test(...)]
- link:https://webpack.js.org/configuration/module/#rule-use[use(...)]
